config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :wallet do
    post :deposit
    post :withdraw
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/notifier.rb
module Notifier
  extend ActiveSupport::Concern

  included do
    def notify_by_email(provider, message)
      provider.send_email('admin@mail.com', message) if provider
    end

    def notify_by_sms()
      response = RestClient.post 'https://private-7898f5-sendsms5.apiary-mock.com/sms', {number: '99999999', message: 'Message from application'}
      JSON.parse(response)
    end
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  include Notifier
  validates :balance, presence: true
  validate :positive_amount

  def deposit(amount)
    raise('Invalid Input') if (amount.to_f == 0 || amount.to_f == 0.0) && (amount != 0 || amount != 0.0)
    self.balance = 0 unless self.balance
    amount = amount.to_f
    raise('Invalid Amount') if amount < 0
    update_attributes(balance: (balance + amount))
    notify_by_sms()
  end

  def withdraw(amount)
    self.balance = 0 unless self.balance
    amount = amount.to_f
    raise('Invalid Amount') if amount < 0
    raise('Amount greater than balance') if amount > balance
    update_attributes(balance: (balance - amount))
    self.reload
    notify_by_email(nil, 'foo bar') if balance <= 0
    notify_by_sms()
  end

  private

  def positive_amount
    if self.balance && self.balance < 0
      errors.add(:balance, 'must be greater than or equal to 0')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :load_wallet

  def deposit
    amount = wallet_params[:amount]
    begin
      @wallet.deposit amount
    rescue RuntimeError => e
      flash[:error] = e.message
    end
    redirect_to wallet_path
  end

  def withdraw
    amount = wallet_params[:amount]
    begin
      @wallet.withdraw amount
    rescue RuntimeError => e
      flash[:error] = e.message
    end
    redirect_to wallet_path
  end

  private

  def load_wallet
    @wallet = Wallet.first
    @wallet = Wallet.create unless @wallet
  end

  def wallet_params
    params.permit(:amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash"><%=flash[:error]%></div>
    <%= yield %>
  </body>
</html>

app/views/wallets/show.html.erb
<h1>Hello Wallet</h1>

<h2>Wallet Balance: <%= @wallet.balance -%></h2>
<div class='deposit'>
  <%=form_tag(deposit_wallet_path) do -%>
    <%=text_field_tag 'amount' -%>
    <%=submit_tag 'Deposit' -%>
  <% end -%>
</div>
<div class='withdraw'>
  <%=form_tag(withdraw_wallet_path) do -%>
    <%=text_field_tag 'amount' -%>
    <%=submit_tag 'Withdraw' -%>
  <% end -%>
</div>